# Agents-Only Mode Configuration
# Pure strategic mode for maximum reasoning capability
# Note: 0% token reduction - full Agent overhead on all queries

mode:
  name: "agents_only"
  description: "Pure Agents mode - maximum strategic reasoning (0% token reduction)"
  default: false

routing:
  enabled: false  # No routing - all queries go to Agents
  force_target: "agent"

skills:
  enabled: false  # Skills disabled in Agents-only mode

  # Note: Skills remain available as data sources for Agents to call
  # but are not used for primary query handling

agents:
  enabled: true

  # Specialized Agents
  specialized:
    - crypto_macro_analyst
    - crypto_vc_analyst
    - crypto_sentiment_analyst

  # Strategic Orchestrator
  orchestrator:
    enabled: true
    agent: "thesis_synthesizer"

    # Auto-invoke orchestrator for complex queries
    auto_invoke: true
    auto_invoke_threshold: 0.80  # If query complexity > 80%, use orchestrator

  # Agent selection strategy
  selection:
    # When query doesn't clearly map to a specific Agent
    default_agent: "crypto_vc_analyst"  # Most comprehensive Agent

    # Fuzzy matching for Agent selection
    fuzzy_match: true
    fuzzy_threshold: 0.70

  # Agent capabilities
  capabilities:
    strategic_reasoning: true
    multi_domain_synthesis: true
    investment_recommendations: true
    risk_assessment: true
    portfolio_optimization: true

performance:
  # Token usage targets
  token_reduction:
    target: 0.0  # 0% reduction - full Agent overhead
    agent_overhead: 1.0  # 100% Agent token usage

  # Expected query distribution
  distribution:
    skills: 0.0
    agents: 0.95  # 95% of queries to specialized Agents
    orchestrator: 0.05  # 5% of queries to Orchestrator

  # Benefits
  benefits:
    - "Full strategic reasoning capability"
    - "Multi-domain synthesis"
    - "Investment-grade recommendations"
    - "Deep due diligence analysis"
    - "Nuanced risk assessment"

  # Trade-offs
  tradeoffs:
    - "No token efficiency gains"
    - "Higher latency per query"
    - "Higher computational cost"
    - "Requires full MCP infrastructure"

mcp:
  # MCP servers used by Agents (comprehensive set)
  servers:
    # Sentiment data
    - name: "crypto-sentiment-mcp"
      required: true
      usage: ["agents"]

    - name: "crypto-feargreed-mcp"
      required: true
      usage: ["agents"]

    # Trading data
    - name: "ccxt-mcp"
      required: true
      usage: ["agents"]

    - name: "crypto-indicators-mcp"
      required: true
      usage: ["agents"]

    # News/content
    - name: "cryptopanic-mcp-server"
      required: true
      usage: ["agents"]

    # Project analysis
    - name: "crypto-projects-mcp"
      required: true
      usage: ["agents"]

    # Macro data (for crypto-macro-analyst)
    - name: "grok-search-mcp"
      required: false
      usage: ["agents"]

    - name: "perplexity"
      required: false
      usage: ["agents"]

logging:
  # Performance tracking
  track_routing_decisions: false  # No routing in this mode
  track_token_usage: true
  track_agent_usage: true
  track_orchestrator_usage: true

  # Log levels
  agents: "INFO"
  orchestrator: "INFO"
  routing: "DISABLED"
  skills: "DISABLED"

# Recommended use cases for Agents-only mode:
# - Professional investment analysis
# - Deep due diligence research
# - Strategic portfolio planning
# - High-stakes trading decisions
# - Institutional-grade analysis
# - When token efficiency is not a constraint
# - Benchmarking/comparison scenarios
